export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  ADMIN: '/admins',
  ANALYTICS: '/analytics',
  CATEGORIES: '/categories',
  COUPONS: '/coupons',
  FILES: '/files',
  NOTIFICATIONS: '/notifications',
  ORDERS: '/orders',
  PRODUCTS: '/products',
  REVIEWS: '/reviews',
  SETTINGS: '/settings',
  USERS: '/users',
} as const
