CREATE TABLE ec.orders
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     uuid,
    total_price integer                                 NOT NULL,
    status      text        DEFAULT 'PENDING'::text,
    created_at  timestamptz DEFAULT now()
);
    -- =========================
-- ec.orders
-- =========================
    COMMENT ON COLUMN "ec"."orders"."id" IS
  '주문의 고유 ID이다. 기본 키로 사용된다.';

COMMENT
ON COLUMN "ec"."orders"."user_id" IS
  '주문을 생성한 사용자 ID이다. 회원 주문이 아닐 경우 NULL일 수 있다.';

COMMENT
ON COLUMN "ec"."orders"."total_price" IS
  '주문 전체의 최종 결제 금액이다.';

COMMENT
ON COLUMN "ec"."orders"."status" IS
  '주문 상태이다. PENDING, PAID, CANCELLED 등으로 결제 및 처리 상태를 구분한다.';

COMMENT
ON COLUMN "ec"."orders"."created_at" IS
  '주문이 생성된 일시이다.';
