CREATE TABLE ec.product_images
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_id   bigint                                  NOT NULL,
    role         ec.product_image_role                   NOT NULL,
    storage_path text                                    NOT NULL,
    sort_order   integer                                 NOT NULL DEFAULT 0,
    alt          text,
    width        integer,
    height       integer,
    mime_type    text,
    created_at   timestamptz                             NOT NULL DEFAULT now()
);
    -- =========================
-- ec.product_images
-- =========================
    COMMENT ON COLUMN "ec"."product_images"."id" IS
  '상품 이미지의 고유 ID이다.';

COMMENT
ON COLUMN "ec"."product_images"."product_id" IS
  '이미지가 연결된 상품 ID이다. products 테이블과 연결된다.';

COMMENT
ON COLUMN "ec"."product_images"."role" IS
  '상품 이미지의 역할을 나타낸다. thumbnail, gallery, description 중 하나이다.';

COMMENT
ON COLUMN "ec"."product_images"."storage_path" IS
  '이미지가 저장된 스토리지 상의 경로이다. Supabase Storage 버킷 내 경로 등에 사용된다.';

COMMENT
ON COLUMN "ec"."product_images"."sort_order" IS
  '상품 이미지가 노출되는 순서이다. 숫자가 작을수록 먼저 노출된다.';

COMMENT
ON COLUMN "ec"."product_images"."alt" IS
  '이미지의 대체 텍스트이다. 접근성 및 SEO 개선을 위해 사용된다.';

COMMENT
ON COLUMN "ec"."product_images"."width" IS
  '이미지의 가로(width) 픽셀 값이다.';

COMMENT
ON COLUMN "ec"."product_images"."height" IS
  '이미지의 세로(height) 픽셀 값이다.';

COMMENT
ON COLUMN "ec"."product_images"."mime_type" IS
  '이미지 파일의 MIME 타입이다. 예: image/jpeg, image/png 등.';

COMMENT
ON COLUMN "ec"."product_images"."created_at" IS
  '상품 이미지 레코드가 생성된 일시이다.';

