CREATE TABLE ec.categories
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       text                                    NOT NULL,
    slug       text                                    NOT NULL,
    parent_id  bigint,
    path public.ltree,
    depth      integer GENERATED ALWAYS AS (nlevel(path)) STORED,
    selectable boolean DEFAULT FALSE
);
    -- =========================
-- ec.categories
-- =========================
    COMMENT ON COLUMN "ec"."categories"."id" IS
  '카테고리의 고유 ID이다. 기본 키로 사용된다.';

COMMENT
ON COLUMN "ec"."categories"."name" IS
  '카테고리 이름이다. 관리자/사용자 화면에 노출되는 명칭이다.';

COMMENT
ON COLUMN "ec"."categories"."slug" IS
  '카테고리 슬러그(slug)이다. URL, 검색, 식별용으로 사용하는 문자열이다.';

COMMENT
ON COLUMN "ec"."categories"."parent_id" IS
  '부모 카테고리 ID이다. 루트 카테고리인 경우 NULL이 된다.';

COMMENT
ON COLUMN "ec"."categories"."path" IS
  'ltree 타입으로 표현된 카테고리 전체 경로이다. 계층 구조 탐색에 사용된다.';

COMMENT
ON COLUMN "ec"."categories"."depth" IS
  '카테고리의 계층 깊이이다. 루트는 1에서 시작하며 path를 기반으로 자동 계산된다.';

COMMENT
ON COLUMN "ec"."categories"."selectable" IS
  '해당 카테고리가 상품의 최종 선택 대상이 될 수 있는지 여부이다. true일 경우 상품에 직접 매핑할 수 있다.';

