CREATE TABLE ec.order_items
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id   bigint,
    product_id bigint,
    quantity   integer                                 NOT NULL,
    price      integer                                 NOT NULL
);
    -- =========================
-- ec.order_items
-- =========================
    COMMENT ON COLUMN "ec"."order_items"."id" IS
  '주문 항목의 고유 ID이다. 기본 키로 사용된다.';

COMMENT
ON COLUMN "ec"."order_items"."order_id" IS
  '해당 항목이 속한 주문의 ID이다. orders 테이블과 연결된다.';

COMMENT
ON COLUMN "ec"."order_items"."product_id" IS
  '주문된 상품의 ID이다. products 테이블과 연결된다.';

COMMENT
ON COLUMN "ec"."order_items"."quantity" IS
  '해당 상품의 주문 수량이다.';

COMMENT
ON COLUMN "ec"."order_items"."price" IS
  '해당 주문 항목의 단가 또는 계산 기준 금액이다. 할인 전/후 금액 정책에 맞게 사용한다.';

