CREATE TABLE ec.tags
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        text                                    NOT NULL,
    slug        text                                    NOT NULL,
    description text,
    color       text,
    is_active   boolean     DEFAULT true,
    created_at  timestamptz DEFAULT now(),
    updated_at  timestamptz DEFAULT now()
);
    -- =========================
-- ec.tags
-- =========================
    COMMENT ON COLUMN "ec"."tags"."id" IS
  '태그의 고유 ID이다. 기본 키로 사용된다.';

COMMENT
ON COLUMN "ec"."tags"."name" IS
  '태그 이름이다. 사용자에게 노출되는 태그 명칭이다.';

COMMENT
ON COLUMN "ec"."tags"."slug" IS
  '태그 슬러그(slug)이다. URL, 검색, 내부 식별용으로 사용하는 문자열이다.';

COMMENT
ON COLUMN "ec"."tags"."description" IS
  '태그에 대한 설명이다. 태그의 의미나 사용 용도를 서술한다.';

COMMENT
ON COLUMN "ec"."tags"."color" IS
  '태그를 표시할 때 사용할 색상 값이다. 예를 들어 HEX 컬러 코드 등을 저장한다.';

COMMENT
ON COLUMN "ec"."tags"."is_active" IS
  '태그 사용 여부이다. true이면 현재 사용 중인 태그이다.';

COMMENT
ON COLUMN "ec"."tags"."created_at" IS
  '태그 레코드가 생성된 일시이다.';

COMMENT
ON COLUMN "ec"."tags"."updated_at" IS
  '태그 레코드가 마지막으로 수정된 일시이다.';

