CREATE TABLE ec.user_coupons
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   uuid                                    NOT NULL,
    coupon_id bigint                                  NOT NULL,
    is_used   boolean                                 NOT NULL DEFAULT false,
    issued_at timestamptz                             NOT NULL DEFAULT now(),
    used_at   timestamptz,
    order_id  bigint
);
    -- =========================
-- ec.user_coupons
-- =========================
    COMMENT ON COLUMN "ec"."user_coupons"."id" IS
  '사용자에게 발급된 쿠폰 인스턴스의 고유 ID이다.';

COMMENT
ON COLUMN "ec"."user_coupons"."user_id" IS
  '쿠폰을 발급받은 사용자 ID이다.';

COMMENT
ON COLUMN "ec"."user_coupons"."coupon_id" IS
  '발급된 쿠폰의 ID이다. coupons 테이블과 연결된다.';

COMMENT
ON COLUMN "ec"."user_coupons"."is_used" IS
  '해당 사용자 쿠폰이 사용되었는지 여부이다. true이면 이미 사용 완료된 상태이다.';

COMMENT
ON COLUMN "ec"."user_coupons"."issued_at" IS
  '쿠폰이 사용자에게 발급된 일시이다.';

COMMENT
ON COLUMN "ec"."user_coupons"."used_at" IS
  '쿠폰이 실제 주문에 사용된 일시이다. 사용 전에는 NULL이다.';

COMMENT
ON COLUMN "ec"."user_coupons"."order_id" IS
  '쿠폰이 사용된 주문의 ID이다. 어떤 주문에 연결되었는지 추적하기 위한 필드이다.';
