CREATE TABLE ec.coupons
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             text                                    NOT NULL,
    description      text,
    discount_type    ec.discount_type                        NOT NULL,
    discount_value   integer                                 NOT NULL,
    max_discount     integer,
    min_order_amount integer,
    is_active        boolean                                 NOT NULL DEFAULT TRUE,
    starts_at        timestamptz,
    ends_at          timestamptz,
    stackable        boolean                                 NOT NULL DEFAULT FALSE,
    max_issue        integer,
    max_redemptions  integer,
    max_per_user     integer                                 NOT NULL DEFAULT 1,
    created_by       uuid,
    notes            text,
    created_at       timestamptz                             NOT NULL DEFAULT now(),
    coupon_kind      ec.coupon_kind                          NOT NULL,
    coupon_code      varchar,
    product_mode     ec.apply_mode                           NOT NULL,
    category_mode    ec.apply_mode
);
    -- =========================
-- ec.coupons
-- =========================
    COMMENT ON COLUMN "ec"."coupons"."id" IS
  '쿠폰의 고유 ID이다. 기본 키로 사용된다.';

COMMENT
ON COLUMN "ec"."coupons"."name" IS
  '쿠폰 이름이다. 관리자 화면과 사용자 화면에서 보여지는 쿠폰명이다.';

COMMENT
ON COLUMN "ec"."coupons"."description" IS
  '쿠폰에 대한 상세 설명이다. 쿠폰 사용 조건이나 안내 문구 등을 적는다.';

COMMENT
ON COLUMN "ec"."coupons"."discount_type" IS
  '쿠폰의 할인 방식이다. rate는 비율(%) 할인, fixed는 정액(고정 금액) 할인, none은 할인 없음이다.';

COMMENT
ON COLUMN "ec"."coupons"."discount_value" IS
  '할인 값이다. discount_type이 rate일 경우 할인율(퍼센트), fixed일 경우 할인 금액을 의미한다.';

COMMENT
ON COLUMN "ec"."coupons"."max_discount" IS
  '할인 시 적용되는 최대 할인 금액 상한이다. 비율 할인(rate)일 때 과도한 할인을 제한하기 위한 값이다.';

COMMENT
ON COLUMN "ec"."coupons"."min_order_amount" IS
  '쿠폰을 사용할 수 있는 최소 주문 금액이다. 해당 금액 이상 주문 시 쿠폰이 적용된다.';

COMMENT
ON COLUMN "ec"."coupons"."is_active" IS
  '쿠폰의 활성 여부이다. true이면 발급/사용이 가능하고, false이면 비활성 상태이다.';

COMMENT
ON COLUMN "ec"."coupons"."starts_at" IS
  '쿠폰 사용 가능 시작 일시이다. 이 시각 이전에는 쿠폰을 사용할 수 없다.';

COMMENT
ON COLUMN "ec"."coupons"."ends_at" IS
  '쿠폰 사용 가능 종료 일시이다. 이 시각 이후에는 쿠폰을 사용할 수 없다.';

COMMENT
ON COLUMN "ec"."coupons"."stackable" IS
  '다른 쿠폰 또는 프로모션과 중복 적용이 가능한지 여부이다. true이면 중복 사용 허용이다.';

COMMENT
ON COLUMN "ec"."coupons"."max_issue" IS
  '해당 쿠폰이 전체적으로 발급될 수 있는 최대 수량이다. 제한이 없으면 NULL로 둘 수 있다.';

COMMENT
ON COLUMN "ec"."coupons"."max_redemptions" IS
  '해당 쿠폰이 전체적으로 사용될 수 있는 최대 횟수이다. 발급 수량과는 별도로 실제 사용량을 제한할 때 사용한다.';

COMMENT
ON COLUMN "ec"."coupons"."max_per_user" IS
  '한 사용자당 보유하거나 사용할 수 있는 최대 쿠폰 개수 또는 사용 가능 횟수이다. 기본값은 1이다.';

COMMENT
ON COLUMN "ec"."coupons"."created_by" IS
  '쿠폰을 생성한 관리자 또는 시스템 유저의 ID이다. 감사 로그 및 추적용으로 사용한다.';

COMMENT
ON COLUMN "ec"."coupons"."notes" IS
  '쿠폰에 대해 내부 운영자가 남기는 메모용 필드이다. 사용자에게는 노출되지 않는다.';

COMMENT
ON COLUMN "ec"."coupons"."created_at" IS
  '쿠폰 레코드가 생성된 일시이다.';

COMMENT
ON COLUMN "ec"."coupons"."coupon_kind" IS
  '쿠폰의 종류를 나타낸다. general은 일반 쿠폰, code는 코드 입력형 쿠폰을 의미한다.';

COMMENT
ON COLUMN "ec"."coupons"."coupon_code" IS
  '코드 입력형 쿠폰에서 사용되는 문자열 코드이다. 일반 쿠폰(general)에서는 NULL일 수 있다.';

COMMENT
ON COLUMN "ec"."coupons"."product_mode" IS
  '해당 상품이 쿠폰 적용 대상인지 제외 대상인지 나타내는 필드이다. apply_mode ENUM을 사용한다.';

COMMENT
ON COLUMN "ec"."coupons"."category_mode" IS
  '해당 카테고리가 쿠폰 적용 대상인지 제외 대상인지 나타내는 필드이다. apply_mode ENUM을 사용한다.';
