CREATE TABLE ec.products
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          text                                    NOT NULL,
    description   text,
    price         bigint                                  NOT NULL,
    sale_price    bigint,
    sale_rate     integer,
    stock         bigint,
    likes         bigint,
    created_at    timestamptz                                      DEFAULT now(),
    status        ec.product_status                                DEFAULT 'hidden'::ec.product_status,
    discount_type ec.discount_type                        NOT NULL DEFAULT 'none'::ec.discount_type
);
    -- =========================
-- ec.products
-- =========================
    COMMENT ON COLUMN "ec"."products"."id" IS
  '상품의 고유 ID이다. 기본 키로 사용된다.';

COMMENT
ON COLUMN "ec"."products"."name" IS
  '상품 이름이다. 리스트 및 상세 화면에 노출되는 대표 명칭이다.';

COMMENT
ON COLUMN "ec"."products"."description" IS
  '상품 상세 설명이다. 텍스트 기반의 설명 정보를 담는다.';

COMMENT
ON COLUMN "ec"."products"."price" IS
  '상품의 기본 판매가이다. 할인이 적용되기 전 기준 가격이다.';

COMMENT
ON COLUMN "ec"."products"."sale_price" IS
  '할인 적용 후 판매가이다. 별도 금액을 지정하고 싶을 때 사용한다.';

COMMENT
ON COLUMN "ec"."products"."sale_rate" IS
  '할인율을 나타내는 정수 값이다. 예를 들어 10이면 10% 할인이다.';

COMMENT
ON COLUMN "ec"."products"."stock" IS
  '현재 재고 수량이다. 재고 관리 및 품절 처리에 사용된다.';

COMMENT
ON COLUMN "ec"."products"."likes" IS
  '상품에 대한 좋아요 또는 찜 카운트이다.';

COMMENT
ON COLUMN "ec"."products"."created_at" IS
  '상품 레코드가 생성된 일시이다.';

COMMENT
ON COLUMN "ec"."products"."status" IS
  '상품의 노출 및 판매 상태이다. active, hidden, sold-out 값으로 상태를 구분한다.';

COMMENT
ON COLUMN "ec"."products"."discount_type" IS
  '상품 수준에서 적용되는 할인 타입이다. rate, fixed, none과 같이 할인 방식 종류를 나타낸다.';
