export const SECTION_NAME = {
  LOGIN: 'LOGIN',

  // Overview
  DASHBOARD: 'DASHBOARD',
  ANALYTICS: 'ANALYTICS',
  REALTIME: 'REALTIME',
  REPORTS: 'REPORTS',

  // Commerce
  ORDERS: 'ORDERS',
  PRODUCTS: 'PRODUCTS',
  CATEGORIES: 'CATEGORIES',
  COUPONS: 'COUPONS',
  REVIEWS: 'REVIEWS',
  USERS: 'USERS',
  SHIPPING: 'SHIPPING',
  SETTLEMENTS: 'SETTLEMENTS',
  MEMBERSHIP: 'MEMBERSHIP',

  // ETC / Marketing
  NOTIFICATIONS: 'NOTIFICATIONS',
  FILES: 'FILES',
  BANNERS: 'BANNERS',
  CAMPAIGNS: 'CAMPAIGNS',
  PAGES: 'PAGES',
  SUPPORT: 'SUPPORT',

  // System
  ADMINS: 'ADMINS',
  SETTINGS: 'SETTINGS',
  ROLES: 'ROLES',
  AUDIT_LOGS: 'AUDIT_LOGS',
  SYSTEM_STATUS: 'SYSTEM_STATUS',
} as const
